version: "3.1"
services:
  kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - uptime_kuma:/app/data

volumes:
  uptime_kuma:
